<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="NETCHAND-G2454" failures="1" tests="5" name="Personal loan" time="0.119" errors="0" timestamp="2020-11-23T13:18:41 IST">
  <testcase classname="test.Day2" name="ploan" time="0.01"/>
  <testcase classname="test.dayone1" name="Demo" time="0.013">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.dayone1.Demo(dayone1.java:26)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.Day4" name="LoginAPIHomeLoan" time="0.003"/>
  <testcase classname="test.Day4" name="MobileLoginHomeLoan" time="0.003"/>
  <testcase classname="test.Day4" name="WebloginHomeLoan" time="0.002"/>
  <testcase classname="test.dayone1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
